// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/plugin/proto/greeter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_plugin_proto_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_greeter_proto_rawDescGZIP(), []int{0}
}

// GreetingResponse contains the greeting message
type GreetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetingResponse) Reset() {
	*x = GreetingResponse{}
	mi := &file_pkg_plugin_proto_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingResponse) ProtoMessage() {}

func (x *GreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingResponse.ProtoReflect.Descriptor instead.
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GreetingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_plugin_proto_greeter_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/plugin/proto/greeter.proto\x12\agreeter\"\a\n" +
	"\x05Empty\",\n" +
	"\x10GreetingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa8\x02\n" +
	"\x0eGreeterService\x122\n" +
	"\x05Hello\x12\x0e.greeter.Empty\x1a\x19.greeter.GreetingResponse\x128\n" +
	"\vGoodMorning\x12\x0e.greeter.Empty\x1a\x19.greeter.GreetingResponse\x12:\n" +
	"\rGoodAfternoon\x12\x0e.greeter.Empty\x1a\x19.greeter.GreetingResponse\x126\n" +
	"\tGoodNight\x12\x0e.greeter.Empty\x1a\x19.greeter.GreetingResponse\x124\n" +
	"\aGoodBye\x12\x0e.greeter.Empty\x1a\x19.greeter.GreetingResponseB-Z+github.com/unsuman/greeter/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_greeter_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_greeter_proto_rawDescData []byte
)

func file_pkg_plugin_proto_greeter_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_greeter_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_greeter_proto_rawDesc), len(file_pkg_plugin_proto_greeter_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_greeter_proto_rawDescData
}

var file_pkg_plugin_proto_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_plugin_proto_greeter_proto_goTypes = []any{
	(*Empty)(nil),            // 0: greeter.Empty
	(*GreetingResponse)(nil), // 1: greeter.GreetingResponse
}
var file_pkg_plugin_proto_greeter_proto_depIdxs = []int32{
	0, // 0: greeter.GreeterService.Hello:input_type -> greeter.Empty
	0, // 1: greeter.GreeterService.GoodMorning:input_type -> greeter.Empty
	0, // 2: greeter.GreeterService.GoodAfternoon:input_type -> greeter.Empty
	0, // 3: greeter.GreeterService.GoodNight:input_type -> greeter.Empty
	0, // 4: greeter.GreeterService.GoodBye:input_type -> greeter.Empty
	1, // 5: greeter.GreeterService.Hello:output_type -> greeter.GreetingResponse
	1, // 6: greeter.GreeterService.GoodMorning:output_type -> greeter.GreetingResponse
	1, // 7: greeter.GreeterService.GoodAfternoon:output_type -> greeter.GreetingResponse
	1, // 8: greeter.GreeterService.GoodNight:output_type -> greeter.GreetingResponse
	1, // 9: greeter.GreeterService.GoodBye:output_type -> greeter.GreetingResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_greeter_proto_init() }
func file_pkg_plugin_proto_greeter_proto_init() {
	if File_pkg_plugin_proto_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_greeter_proto_rawDesc), len(file_pkg_plugin_proto_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_greeter_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_greeter_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_greeter_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_greeter_proto = out.File
	file_pkg_plugin_proto_greeter_proto_goTypes = nil
	file_pkg_plugin_proto_greeter_proto_depIdxs = nil
}
