// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/plugin/proto/greeter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreeterService_Hello_FullMethodName         = "/greeter.GreeterService/Hello"
	GreeterService_GoodMorning_FullMethodName   = "/greeter.GreeterService/GoodMorning"
	GreeterService_GoodAfternoon_FullMethodName = "/greeter.GreeterService/GoodAfternoon"
	GreeterService_GoodNight_FullMethodName     = "/greeter.GreeterService/GoodNight"
	GreeterService_GoodBye_FullMethodName       = "/greeter.GreeterService/GoodBye"
)

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GreeterService defines the interface for language-specific greeters
type GreeterServiceClient interface {
	Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
	GoodMorning(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
	GoodAfternoon(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
	GoodNight(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
	GoodBye(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error)
}

type greeterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterServiceClient(cc grpc.ClientConnInterface) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) Hello(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreeterService_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) GoodMorning(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreeterService_GoodMorning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) GoodAfternoon(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreeterService_GoodAfternoon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) GoodNight(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreeterService_GoodNight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) GoodBye(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GreetingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, GreeterService_GoodBye_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServiceServer is the server API for GreeterService service.
// All implementations must embed UnimplementedGreeterServiceServer
// for forward compatibility.
//
// GreeterService defines the interface for language-specific greeters
type GreeterServiceServer interface {
	Hello(context.Context, *Empty) (*GreetingResponse, error)
	GoodMorning(context.Context, *Empty) (*GreetingResponse, error)
	GoodAfternoon(context.Context, *Empty) (*GreetingResponse, error)
	GoodNight(context.Context, *Empty) (*GreetingResponse, error)
	GoodBye(context.Context, *Empty) (*GreetingResponse, error)
	mustEmbedUnimplementedGreeterServiceServer()
}

// UnimplementedGreeterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServiceServer struct{}

func (UnimplementedGreeterServiceServer) Hello(context.Context, *Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedGreeterServiceServer) GoodMorning(context.Context, *Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodMorning not implemented")
}
func (UnimplementedGreeterServiceServer) GoodAfternoon(context.Context, *Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodAfternoon not implemented")
}
func (UnimplementedGreeterServiceServer) GoodNight(context.Context, *Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodNight not implemented")
}
func (UnimplementedGreeterServiceServer) GoodBye(context.Context, *Empty) (*GreetingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodBye not implemented")
}
func (UnimplementedGreeterServiceServer) mustEmbedUnimplementedGreeterServiceServer() {}
func (UnimplementedGreeterServiceServer) testEmbeddedByValue()                        {}

// UnsafeGreeterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServiceServer will
// result in compilation errors.
type UnsafeGreeterServiceServer interface {
	mustEmbedUnimplementedGreeterServiceServer()
}

func RegisterGreeterServiceServer(s grpc.ServiceRegistrar, srv GreeterServiceServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreeterService_ServiceDesc, srv)
}

func _GreeterService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).Hello(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_GoodMorning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).GoodMorning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_GoodMorning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).GoodMorning(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_GoodAfternoon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).GoodAfternoon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_GoodAfternoon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).GoodAfternoon(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_GoodNight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).GoodNight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_GoodNight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).GoodNight(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_GoodBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).GoodBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterService_GoodBye_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).GoodBye(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GreeterService_ServiceDesc is the grpc.ServiceDesc for GreeterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GreeterService_Hello_Handler,
		},
		{
			MethodName: "GoodMorning",
			Handler:    _GreeterService_GoodMorning_Handler,
		},
		{
			MethodName: "GoodAfternoon",
			Handler:    _GreeterService_GoodAfternoon_Handler,
		},
		{
			MethodName: "GoodNight",
			Handler:    _GreeterService_GoodNight_Handler,
		},
		{
			MethodName: "GoodBye",
			Handler:    _GreeterService_GoodBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/proto/greeter.proto",
}
